In [17]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot


In [18]:
### sentences
sent=[ 'the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good',]

In [19]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [20]:
# Define the vocabulary size
voc_size= 10000


In [21]:
# One hot representation for every word
onehot_rep = [one_hot(words,voc_size) for words in sent]
onehot_rep

[[9607, 457, 4337, 7483],
 [9607, 457, 4337, 823],
 [9607, 261, 4337, 1011],
 [6, 4795, 5392, 6525, 5958],
 [6, 4795, 5392, 6525, 872],
 [5300, 9607, 5309, 4337, 8289],
 [9620, 9757, 3888, 6525]]

In [22]:
# Word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [23]:
sent_length = 8
embedded_docs = pad_sequences(onehot_rep, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9607  457 4337 7483]
 [   0    0    0    0 9607  457 4337  823]
 [   0    0    0    0 9607  261 4337 1011]
 [   0    0    0    6 4795 5392 6525 5958]
 [   0    0    0    6 4795 5392 6525  872]
 [   0    0    0 5300 9607 5309 4337 8289]
 [   0    0    0    0 9620 9757 3888 6525]]


In [24]:
# Feature representation
dim = 10
model= Sequential()
model.add(Embedding(voc_size, dim, input_shape=(sent_length,)))
model.compile('adam',loss='mse')

In [25]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 248ms/step


array([[[-1.63580887e-02, -3.58493552e-02,  3.59792598e-02,
         -4.84712608e-02,  4.14159633e-02,  4.90470976e-03,
         -1.19101182e-02, -4.57743071e-02, -3.52331996e-02,
         -8.35291296e-03],
        [-1.63580887e-02, -3.58493552e-02,  3.59792598e-02,
         -4.84712608e-02,  4.14159633e-02,  4.90470976e-03,
         -1.19101182e-02, -4.57743071e-02, -3.52331996e-02,
         -8.35291296e-03],
        [-1.63580887e-02, -3.58493552e-02,  3.59792598e-02,
         -4.84712608e-02,  4.14159633e-02,  4.90470976e-03,
         -1.19101182e-02, -4.57743071e-02, -3.52331996e-02,
         -8.35291296e-03],
        [-1.63580887e-02, -3.58493552e-02,  3.59792598e-02,
         -4.84712608e-02,  4.14159633e-02,  4.90470976e-03,
         -1.19101182e-02, -4.57743071e-02, -3.52331996e-02,
         -8.35291296e-03],
        [ 2.00959295e-03, -8.23205709e-03, -3.54106054e-02,
          4.91255634e-02,  4.80305664e-02,  3.42802517e-02,
         -7.51600415e-03,  4.64125387e-02, -4.383640